# fly.toml app configuration file generated for goswirl-app on 2023-07-28T12:02:54+05:30
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "goswirl-app"
primary_region = "ams"

[env]
  PORT = "8081"
  HOST = "https://goswirl-app.fly.dev"
  SHOPIFY_API_KEY = "811de43779faeb764c17e5bce2d28c44"
  SCOPES = "write_products, read_products, read_orders, write_orders"
  SWRILBASEURL = "https://bigleap.live/index.php/APIv1"


[http_service]
  internal_port = 8081
  force_https = true
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 0